config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :original_photos, param: :uuid, only: %i[ index show create destroy ]
  resources :personal_photos

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/aws_client.rb
module AwsClient
  def self.rekognition
    @rekognition ||= Aws::Rekognition::Client.new(
      credentials: Aws::Credentials.new(
        Rails.application.credentials.dig(:aws, :access_key_id),
        Rails.application.credentials.dig(:aws, :secret_access_key)
      ),
      region: "ap-northeast-1"
    )
  end

  def self.s3
    @s3 ||= Aws::S3::Client.new(
      credentials: Aws::Credentials.new(
        Rails.application.credentials.dig(:aws, :access_key_id),
        Rails.application.credentials.dig(:aws, :secret_access_key)
      ),
      region: "ap-northeast-1"
    )
  end
end

app/models/compare.rb
class Compare
  def initialize(original_photo:)
    @rekognition_client = AwsClient.rekognition
    @s3_client = AwsClient.s3
    @original_photo = original_photo
    @bucket_name = "face-swapper-bucket-#{Rails.env}"
  end

  def compare_face_image
    s3_original_photo = @s3_client.get_object(bucket: @bucket_name, key: @original_photo.photo.key)
    image = MiniMagick::Image.read(s3_original_photo.body)
    width, height = image.dimensions

    PersonalPhoto.find_each do |personal_photo|
      attrs = {
        source_image: {
          s3_object: {
            bucket: @bucket_name,
            name: personal_photo.photo.key
          }
        },
        target_image: {
          s3_object: {
            bucket: @bucket_name,
            name: @original_photo.photo.key
          }
        },
        similarity_threshold: 80
      }
      response = @rekognition_client.compare_faces attrs
      next if response.face_matches.blank?

      s3_icon = @s3_client.get_object(bucket: @bucket_name, key: personal_photo.icon.key)
      icon = MiniMagick::Image.read(s3_icon.body)

      response.face_matches.each do |face_match|
        position = face_match.face.bounding_box
        image.combine_options do |c|
          icon_height = height * position.height
          icon_width = icon_height
          face_position_top = position.top * height
          face_center = position.left + position.width / 2
          face_position_left = face_center * width - icon_width / 2
          c.draw "image Over #{face_position_left},#{face_position_top} #{icon_width},#{icon_height} '#{icon.path}'"
        end
      end
    end

    image
  end
end

app/models/original_photo.rb
class OriginalPhoto < ApplicationRecord
  before_create -> { self.uuid = SecureRandom.uuid }

  has_one_attached :photo
  has_one_attached :processed_photo

  validates :uuid, uniqueness: true
  validates :photo, attached: true, processable_image: true, content_type: [ :png, :jpg, :jpeg ], size: { less_than: 10.megabytes }

  def exec_rekognition
    image = Compare.new(original_photo: self).compare_face_image
    filename = "#{photo.filename.to_s.split('.')[0]}_#{Time.now.strftime('%Y%m%d%H%M%S')}.png"
    processed_photo.attach(
      io: StringIO.new(image.to_blob),
      filename:,
      content_type: "image/png"
    )
  end

  def to_param
    uuid
  end
end

app/models/personal_photo.rb
class PersonalPhoto < ApplicationRecord
  has_one_attached :photo
  has_one_attached :icon

  validates :name, presence: true, length: { maximum: 50 }
  validates :photo, attached: true, processable_image: true, content_type: [ :png, :jpg, :jpeg ], size: { less_than: 10.megabytes }
  validates :icon, processable_image: true, content_type: [ :png, :jpg, :jpeg ], aspect_ratio: :square, size: { less_than: 10.megabytes }

  def self.process_icon(uploaded_file)
    icon_image = MiniMagick::Image.read(uploaded_file.tempfile)
    MiniMagick::Tool::Convert.new do |img|
      img.size "#{icon_image.height}x#{icon_image.width}"
      img << "xc:transparent"
      img.fill icon_image.path
      img.draw "translate #{icon_image.height/2}, #{icon_image.width/2} circle 0,0 #{icon_image.width/2},0"
      img.trim
      img << "png:-"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def site_http_basic_authenticate_with
    return unless Rails.env.production?

    authenticate_or_request_with_http_basic("Application") do |name, password|
      name == Rails.application.credentials.dig(:http_basic_auth, :name) && password == Rails.application.credentials.dig(:http_basic_auth, :password)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @original_photo = OriginalPhoto.new
  end
end

app/controllers/original_photos_controller.rb
class OriginalPhotosController < ApplicationController
  before_action :site_http_basic_authenticate_with, only: %i[ index ]
  before_action :set_original_photo, only: %i[ show destroy ]

  # GET /original_photos
  def index
    @original_photos = OriginalPhoto.all
  end

  # GET /original_photos/1
  def show
  end

  # POST /original_photos
  def create
    @original_photo = OriginalPhoto.new(original_photo_params)

    if @original_photo.save
      @original_photo.exec_rekognition
      redirect_to @original_photo, notice: "画像を変換しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /original_photos/1
  def destroy
    @original_photo.destroy!
    redirect_to root_path, notice: "画像を削除しました", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_original_photo
      @original_photo = OriginalPhoto.find_by!(uuid: params.expect(:uuid))
    end

    # Only allow a list of trusted parameters through.
    def original_photo_params
      params.expect(original_photo: [ :photo ])
    end
end

app/controllers/personal_photos_controller.rb
class PersonalPhotosController < ApplicationController
  before_action :site_http_basic_authenticate_with
  before_action :set_personal_photo, only: %i[ show edit update destroy ]

  # GET /personal_photos
  def index
    @personal_photos = PersonalPhoto.all
  end

  # GET /personal_photos/1
  def show
  end

  # GET /personal_photos/new
  def new
    @personal_photo = PersonalPhoto.new
  end

  # GET /personal_photos/1/edit
  def edit
  end

  # POST /personal_photos
  def create
    @personal_photo = PersonalPhoto.new(personal_photo_params)


    if @personal_photo.save
      processed_icon = PersonalPhoto.process_icon(params[:personal_photo][:icon])
      @personal_photo.icon.attach(io: StringIO.new(processed_icon), filename: "#{@personal_photo.id}_#{Time.zone.now.to_i}.png", content_type: "image/png")
      redirect_to @personal_photo, notice: "Personal photo was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /personal_photos/1
  def update
    if @personal_photo.update(personal_photo_params)
      if params[:personal_photo][:icon].present?
        processed_icon = PersonalPhoto.process_icon(params[:personal_photo][:icon])
        @personal_photo.icon.attach(io: StringIO.new(processed_icon), filename: "#{@personal_photo.id}_#{Time.zone.now.to_i}.png", content_type: "image/png")
      end
      redirect_to @personal_photo, notice: "Personal photo was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /personal_photos/1
  def destroy
    @personal_photo.destroy!
    redirect_to personal_photos_path, notice: "Personal photo was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_photo
      @personal_photo = PersonalPhoto.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def personal_photo_params
      params.expect(personal_photo: [ :name, :photo ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.html.erb
<%= form_with(model: original_photo) do |form| %>
  <% if original_photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(original_photo.errors.count, "error") %> prohibited this original_photo from being saved:</h2>

      <ul>
        <% original_photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.file_field :photo, accept: 'image/png,image/jpeg,image/jpg' %>
  </div>

  <div>
    <%= form.submit '変換' %>
  </div>
<% end %>

app/views/home/index.html.erb
<% content_for :title, "Face Swapper - 顔をアイコンに置き換えるアプリ" %>

<h1>Face Swapper</h1>
<p>顔をアイコンに置き換えるアプリ</p>

<%= render "form", original_photo: @original_photo %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Face Swapper" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%# stylesheet_link_tag "application" %>
  </head>

  <body>
    <div style="margin: auto; width: 100%; max-width: 700px; padding: 10px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/original_photos/_form.html.erb
<%= form_with(model: original_photo) do |form| %>
  <% if original_photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(original_photo.errors.count, "error") %> prohibited this original_photo from being saved:</h2>

      <ul>
        <% original_photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo, accept: 'image/png,image/jpeg,image/jpg' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/original_photos/_original_photo.html.erb
<div id="<%= dom_id original_photo %>">
  <% if original_photo.processed_photo.attached? %>
    <%= image_tag original_photo.processed_photo, width: "100%" %>
  <% end %>
</div>

app/views/original_photos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Original photos" %>

<h1>Original photos</h1>

<div id="original_photos">
  <% @original_photos.each do |original_photo| %>
    <% if original_photo.processed_photo.attached? %>
      <p>
        <%= link_to(image_tag(original_photo.processed_photo.variant(resize_to_fit: [500, 300]).processed), original_photo) %>
      </p>
    <% end %>
  <% end %>
</div>

<%= link_to "New original photo", root_path %>

app/views/original_photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @original_photo %>

<div>
  <%= button_to "画像を削除", @original_photo, method: :delete %>
</div>

app/views/personal_photos/_form.html.erb
<%= form_with(model: personal_photo) do |form| %>
  <% if personal_photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(personal_photo.errors.count, "error") %> prohibited this personal_photo from being saved:</h2>

      <ul>
        <% personal_photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo, accept: 'image/png,image/jpeg,image/jpg' %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon, accept: 'image/png,image/jpeg,image/jpg' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/personal_photos/_personal_photo.html.erb
<div id="<%= dom_id personal_photo %>">
  <p>
    <strong>Name:</strong>
    <%= personal_photo.name %>
  </p>

  <% if personal_photo.photo.attached? %>
    <p>
      <strong>Photo:</strong>
      <%= image_tag personal_photo.photo, width: "100%" %>
    </p>
  <% end %>

  <% if personal_photo.icon.attached? %>
    <p>
      <strong>Icon:</strong>
      <%= image_tag personal_photo.icon, width: "100%" %>
    </p>
  <% end %>
</div>

app/views/personal_photos/edit.html.erb
<% content_for :title, "Editing personal photo" %>

<h1>Editing personal photo</h1>

<%= render "form", personal_photo: @personal_photo %>

<br>

<div>
  <%= link_to "Show this personal photo", @personal_photo %> |
  <%= link_to "Back to personal photos", personal_photos_path %>
</div>

app/views/personal_photos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Personal photos" %>

<h1>Personal photos</h1>

<div id="personal_photos">
  <% @personal_photos.each do |personal_photo| %>
    <p>
      <%= link_to personal_photo.name, personal_photo %>
      <% if personal_photo.icon.attached? %>
        <%= image_tag personal_photo.icon.variant(resize:'50x50').processed %>
      <% end %>
    </p>
  <% end %>
</div>

<%= link_to "New personal photo", new_personal_photo_path %>

app/views/personal_photos/new.html.erb
<% content_for :title, "New personal photo" %>

<h1>New personal photo</h1>

<%= render "form", personal_photo: @personal_photo %>

<br>

<div>
  <%= link_to "Back to personal photos", personal_photos_path %>
</div>

app/views/personal_photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @personal_photo %>

<div>
  <%= link_to "Edit this personal photo", edit_personal_photo_path(@personal_photo) %> |
  <%= link_to "Back to personal photos", personal_photos_path %>

  <%= button_to "Destroy this personal photo", @personal_photo, method: :delete %>
</div>